name: "publish"

on:
  release:
    types: [published]

jobs:
  release:
     name: publish
     runs-on: ubuntu-latest
     steps:
      - name: checkout
        uses: actions/checkout@v2.3.4
      - name: setup node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: '16'
          registry-url: https://registry.npmjs.org
      - name: publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
